### ISSUE TITLE
`extern "C"` required

### ISSUE THREAD

**Issue by vain** [Aeva/webkit2gtk-experiment#1]
Disclaimer: I am by no means a C++ expert, I’m only familiar with C. I’d like to encourage you to do some more research on this topic on your own.

That being said, I think I have an idea why your web extension isn’t loading. When you check the exported symbols of your module, you’ll see the following:

```
$ nm -D module.so 
...
0000000000000a10 T _Z31webkit_web_extension_initializeP19_WebKitWebExtension
...
```

Note the `_Z31` prefix and the `P19...` suffix. The WebKit library probably won’t be able to find that symbol.

Instead, when prefixing the function with `extern "C"`, you’ll get this:

```
$ nm -D module.so 
...
0000000000000960 T webkit_web_extension_initialize
...
```

Now, the extension will be loaded and output on stdout is shown. (Even lariza can pick up the module.)

Here’s the diff:

``` diff
diff --git a/module.cpp b/module.cpp
index 1b674d2..4b2220e 100644
--- a/module.cpp
+++ b/module.cpp
@@ -57,7 +57,7 @@ window_object_cleared_callback (WebKitScriptWorld *world,
 //
 //  Extension initialization thing.
 //
-G_MODULE_EXPORT void
+extern "C" G_MODULE_EXPORT void
 webkit_web_extension_initialize (WebKitWebExtension *extension)
 {
     std::cout << "EXTENSION INITIALIZED\n";
```

**Comment by Aeva** [comment]
And that fixes it!  I forgot all about name mangling >_<
Thank you so much, this is a huge help! :)
